### ISSUE TITLE
El programa deja de funcionar al intentar procesar un archivo de sonido en blanco

### ISSUE THREAD

**Issue by LuishMC** [ComunidadAylas/PackSquash#101]
**Describir el error**
Existen muchos paquetes de recursos que usan archivos de sonidos en blanco para deshabilitar un sonido en específico del juego. Al intentar optimizarlos, el programa solamente se detiene.

**Para reproducir**
1. Descargar el archivo adjunto al problema (encontrado abajo) y descomprimirlo
2. Añadir el archivo a algún paquete de recursos
3. Optimizar el paquete de recursos

**Archivos adjuntos**
[sonido_en_blanco.zip](https://github.com/ComunidadAylas/PackSquash/files/8572233/sonido_en_blanco.zip)

**Comment by LuishMC** [comment]
> En particular, el sonido en blanco que has adjuntado a esta incidencia funciona correctamente con la última versión de PackSquash, puesto que es "falso": en realidad contiene una décima de segundo de casi completo silencio. Lo he probado.
> 
> Podría ayudar que adjuntases un sonido en blanco "auténtico", que estás totalmente seguro de que la última versión de PackSquash no puede procesar, para que lo analice en detalle y vea si es posible hacer que se comporte mejor. También está en mis planes cambiar las bibliotecas que PackSquash utiliza para procesar audio, pero a priori no puedo garantizar que ello arregle esta situación.

Que extraño, pues a mi no me funcionó ese archivo. Dame un poco de tiempo y tal vez encuentre otro.

**Comment by AlexTMjugador** [comment]
Que PackSquash continúe procesando el paquete aún tras encontrar un problema es arriesgado, pues ello podría redundar en resultados inconsistentes y paquetes rotos, aunque originalmente no lo estuviesen. Aunque entiendo que de primeras se hace pesado tener que ir arreglando los errores, a la larga merece la pena.

Cuando sea previsible que puedan ocurrir errores es muy recomendable abrir PackSquash de forma que no cierre su ventana al salir, para que puedas saber qué ha pasado.

**Comment by AlexTMjugador** [comment]
Como parte de los cambios en 61de25ed50b011a6732ae4e0edfd704943bb2005, ahora PackSquash puede procesar ficheros de sonido en blanco de ambos tipos, y también los optimiza mejor: si detecta que un sonido contiene silencio absoluto, lo sustituye por un fichero sin datos de audio válido especialmente diseñado para ser lo más pequeño posible.

Considero que esta incidencia está, pues, resuelta.
