### ISSUE TITLE
GitHub Actions Support

### ISSUE THREAD

**Issue by deeprobin** [ComunidadAylas/PackSquash#11]
An GitHub Actions "module" would be nice for automating build pipelines 😄.

**Comment by AlexTMjugador** [comment]
[We already use GitHub Actions for continuous integration](https://github.com/ComunidadAylas/PackSquash/actions), which helps testing that the code builds (and, in the upcoming version, runs) fine not only on my computer, and serves as documentation for the build process. In fact, the official PackSquash binaries are built in this GitHub Actions environment. Are you thinking about something different that is not already implemented?

**Comment by deeprobin** [comment]
@AlexTMjugador I actually meant a custom GitHub action that others can add to their repository to e.g. automatically squash a resource pack and then release it.

**Comment by AlexTMjugador** [comment]
Oh, I understand now. It's actually a great idea. I'm adding this issue to the roadmap, although I'm not planning it for any specific time or release. Thanks!

**Comment by sya-ri** [comment]
I developed https://github.com/sya-ri/action-PackSquash. We look forward to helping you ❤️

**Comment by AlexTMjugador** [comment]
That action looks very nice, @sya-ri! Great work! :+1: 

However, I've plans to release PackSquash v0.3.0 soon, which will introduce some backwards incompatible changes to the available options in the settings file, so it'd be nice to sync the v0.3.0 release with your action. Also, I'm interested in making this action look more "official", by moving it to this repository (via a PR, for example), to another repository within PackSquash' organization, or something similar. If you're interested in these matters, please contact me via any of the methods described in the `README.md` file, or open a [discussion](https://github.com/ComunidadAylas/PackSquash/discussions) if you prefer (although I usually respond faster over Discord).

**Comment by AlexTMjugador** [comment]
@sya-ri and I have just released the official GitHub Action for PackSquash in this repository: https://github.com/ComunidadAylas/PackSquash-action. This new action basically made the work that sya has already put on his own official, so it now has my blessing, review and encouragement to use, which should help in making it stay updated with upcoming PackSquash releases, like the imminent v0.3.0. @sya-ri has commit access to that repository and is free to maintain it however he likes to, although I retain the final say on what is pushed to release branches, and I can do changes myself if needed.

I'm closing this issue as resolved, then. Feel free to test the new action and give us feedback!
