### ISSUE TITLE
I found a server that has some extreme pack corruption, I am virtually unable to decompress it even with JD-GUI

### ISSUE THREAD

**Issue by DarkReaper231** [ComunidadAylas/PackSquash#195]
### Related problem or need

I don't know how it works, it's used by server called TropicLand but it is the strongest corruption I have ever seen and none of my friends were able to decopress it even tho they did manage to decopress other corruption methods.

### Proposed solution

Add such corruption method into PackSquash

### Alternative solutions

I couldn't figure out how they do it so if you could tell me, I might make my own Java tool for that instead. Some open source references would be nice too. I didn't find any repos that are specifically aimed at resource pack corruption.

### Additional context

Here is the zip file for study

[tropicland.zip](https://github.com/ComunidadAylas/PackSquash/files/10711327/tropicland.zip)

**Comment by AlexTMjugador** [comment]
Hi! Thank you for taking the time to write this issue!

After analyzing the ZIP file you attached, I can confirm that the latest PackSquash version can create ZIP files of equivalent extraction difficulty. Therefore, such an analysis did not help to develop better protection techniques. For security reasons, I refuse to disclose technical details of how PackSquash implements its ZIP file protection feature.

If your goal is to generate pack ZIPs as protected as the one you attached, rest assured that PackSquash is the right tool for the job, especially if you read its documentation carefully :wink:

Still, I appreciate your feedback. If you find other ZIP files that may help improve PackSquash, feel free to get back in touch, preferably over Discord. The repository README mentions the required contact information.
