### ISSUE TITLE
Special characters in German language translation are considered as surrogates and halt compression

### ISSUE THREAD

**Issue by qdpy** [ComunidadAylas/PackSquash#340]
### Distribution

N/A (the distribution does not matter; please explain why if it's not obvious)

### Bug description

The de_de.json translation file contains special characters that are considered as lone leading surrogates, which leads to JSON parsing errors and stops compression. The error message is as follows:

`! assets/minecraft/lang/de_de.json: JSON error: lone leading surrogate in hex escape at line 1 column 22445`

"F\u00fcnfbl\u00e4ttriges Kleeblatt"

### Reproduction steps

Compress the pack

### Expected behavior

-

**Comment by AlexTMjugador** [comment]
PackSquash supports Latin letters with diaeresis in their escaped form, along with most other characters from the Basic Multilingual Plane (BMP), as expected. I verified this by creating a pack file at `assets/minecraft/lang/de_de.json` with the following content: `"F\u00fcnfbl\u00e4ttriges Kleeblatt"`. PackSquash processed the file successfully.

If you can reproduce this same result on your end, which I consider extremely likely, the issue cannot stem from these specific characters. Moreover, the high column count in the error message suggests that the file is a minified, non-vanilla JSON, which can make pinpointing the exact error location and cause more difficult, so could you attach the problematic file for analysis? I don't see this issue being investigated further without clear evidence of its source.

**Comment by AlexTMjugador** [comment]
Closing this, as some time has passed and I couldn’t reproduce an actionable issue. If this is still relevant, feel free to leave a comment so I know that I should continue working on this.
