### ISSUE TITLE
Support for MTR Mod

### ISSUE THREAD

**Issue by Kenny-Hui** [ComunidadAylas/PackSquash#42]
**What is this mod about**
The [MTR Mod](https://www.curseforge.com/minecraft/mc-mods/minecraft-transit-railway) is a 1.16.5+ Fabric Mod that adds automated scheduled train into the game, with its focus on simulating a functional Rapid Transit network.

**What needs to be supported**
In the latest preview of the MTR Mod, player are allowed to create a train using [Blockbench](https://www.blockbench.net/), a 3D modelling software, then export it as a `.bbmodel` format for the MTR Mod to parse the model.

However PackSquash does not support the `.bbmodel` file format at the moment.
This means it's not possible to make a resource pack using PackSquash with a custom train.
Therefore, the `.bbmodel` file format needs to be supported in order for the mod to be functioning as it is.

**Why should this mod be supported**
With how powerful PackSquash functionality is and the growing community of the MTR Mod, not only normal players who created a resource pack with custom train will benefit from the size reduction PackSquash offers, but large servers running the MTR Mod can also compress/protect their resource pack, speeding up the auto download of the resource pack and prevent less knowledgeable players from "stealing" the assets that takes weeks or even months to create.

**What if PackSquash does not support it**
While it may not be a deal breaker for normal player distributing optional resource packs that only contains 1-2 custom train (As they can just choose not to use PackSquash), larger servers would either have to distribute as 2 different resource packs, with custom trains not being able to be compressed/protected, or the servers would have to give up on the significant compression and protection PackSquash provides on other vanilla assets.

You're more welcome to leave a feedback here if you have any comments/issues regarding to MTR Mod Support

**Comment by AlexTMjugador** [comment]
The latest commits add MTR3 support, and leverage the already existing JSON debloating feature to remove keys in `.bbmodel` files that are not parsed by the mod, thus helping reduce file sizes further. As side effects, those models are also harder to open as usual in Blockbench, and some private data was removed from them.

Feedback about the mod support would be appreciated.

**Comment by Kenny-Hui** [comment]
Works perfectly here on the latest MTR Mod preview version, thanks

**Comment by AlexTMjugador** [comment]
I'm closing this issue as this suggestion was implemented in the latest, publicly available unstable builds, and doing so is more consistent and provides for better work tracking. In any case, however, feel free to reopen the issue if you wish to share some suggestion or problem related to MTR support.
