### ISSUE TITLE
Merge Json

### ISSUE THREAD

**Issue by nathanosoares** [ComunidadAylas/PackSquash#96]
To avoid large json files,  my suggestion is to add an option to merge json files.

Like:
```
# All json files with suffix [_font_part]
['**/*?_font_part.json'] 
target_merge_file = 'minecraft/font/default.json'

# All json files in  /models/custom/furnitures/ folder with suffix [_paper_part]
['**/models/custom/furniture/*?_paper_part.json']
target_merge_file = 'minecraft/models/item/paper.json'
```

**Comment by nathanosoares** [comment]
Imagine this example:

`models/item/paper.json`
https://pastebin.com/m5ZzJUSG

I use "custom_model_data" property to create a new item.
It's impossible to manage everything in a single file.

It would be better if I could separate into files:
`models/item/custom/buttons_paper_part.json`
`models/item/custom/acessories_paper_part.json`
`models/item/custom/wearables_paper_part.json`
`models/item/custom/minions_paper_part.json`

This files followed the structure:
`models/item/custom/*_paper_part.json`:
```json
{
    "overrides": [
        // Overrides...
    ]
}
```
`models/item/paper.json`:
```json
{
    "parent": "item/generated",
    "textures": {
        "layer0": "item/paper"
    }
}
```

The result would be https://pastebin.com/m5ZzJUSG

**Comment by AlexTMjugador** [comment]
Thanks for the example. I understand that keeping a lot of overrides in a single model file can get a bit painful when authoring packs and that a way to keep that noise to the minimum is warranted.

Sadly, however, I don't think such an improvement is in scope for this project. PackSquash strives to do one thing well: optimizing packs in size and other measurable characteristics and validating that they are well-formed, like a compiler for a programming language would do. PackSquash should not have features whose only purpose is to change how authors create packs, even if those features overcome shortcomings and inelegances of Minecraft asset formats. In other words, people should only depend on PackSquash for making their packs more optimized, not for any ad-hoc way of extending asset formats or processing them. Incidentally, the main reason PackSquash accepts comments in JSON files, besides their usefulness for pack authors, is that Minecraft parses JSON files leniently and allows them. By limiting the scope of PackSquash in this way, I hope to mitigate [feature creep](https://en.wikipedia.org/wiki/Feature_creep) concerns and keep PackSquash as transparent to end-users as possible.

That being said, my approach for merging overrides into a single JSON file would be to use the free and open-source [`jq`](https://stedolan.github.io/jq/) command-line tool, which is excellent for this and other kinds of JSON file mangling. Playing around with it for a bit, I've come across a `jq` filter that exactly does what you are looking for:

```shell
$ jq -s '.[0] + { overrides: [ .[1:][].overrides[] ] }' paper.json *_paper_part.json
```
![jq filter for merging JSON item model overrides in action](https://user-images.githubusercontent.com/7822554/162939935-63fad33b-c7dd-4d5b-9369-8d4457927b99.png)

### `paper.json` file contents
```json
{
  "parent": "item/generated",
  "textures": {
    "layer0": "item/paper"
  }
}
```

### `*_paper_part.json` files contents
```json
{
  "overrides": [
    {
      "predicate": {
        "custom_model_data": 1
      },
      "model": "custom/ui/buttons/play_button"
    }
  ]
}
```
```json
{
  "overrides": [
    {
      "predicate": {
        "custom_model_data": 12000
      },
      "model": "custom/npc/bank_piglin"
    }
  ]
}
```

That `jq` filter works by:
- Keeping the first input JSON file as-is (`.[0]`).
- Adding or replacing its `overrides` key (`+ { overrides: ... }`) with an array that is generated from concatenating together the values of the `overrides` key in the second and next JSON files (`[ .[1:][].overrides[] ]`).

You can run this `jq` filter before PackSquash. If you are using PackSquash on a GitHub Actions CI workflow, it's useful to note that the GitHub-hosted Ubuntu runners already have `jq` installed.

If you agree that this `jq` filter works for you, I may consider mentioning it on the PackSquash wiki, which has [an article](https://github.com/ComunidadAylas/PackSquash/wiki/Tips-and-resources-for-pack-authoring) with tips and resources for pack authors. In that article, you can already find a Python script to replace all Minecraft languages, generously contributed by @Derkades.

**Comment by AlexTMjugador** [comment]
I'm glad to hear that! For the reasons stated above, I consider this suggestion resolved now.

Feel free to open new issues for any other problems or ideas you might have about PackSquash!
