### ISSUE TITLE
The code can't be processed because ___ is missing

### ISSUE THREAD

**Issue by StormDragon-64** [ComunidadAylas/PackSquash#97]
**Describe the bug**
After I downloaded 0.3.1(Windowsx64) from this GitHub page, I ran the exe (after I extracted the zip) and it said the code couldn't be processed because libg___.dll is missing. There were multiple errors with a different thing where I put the blank.

**To Reproduce**
Download 0.3.1(Windowsx64)
attempt to run the exe
you get an error

**Expected behavior**
The program would start.

**Attached files**
![image](https://user-images.githubusercontent.com/80718549/163745503-056d57b9-0aa0-4170-8e6d-f28c0b70241c.png)

**Comment by AlexTMjugador** [comment]
PackSquash needs the DLLs you've seen in those errors, which are part of GStreamer, a multimedia processing framework, to be installed on the system. This would normally be done by an installer, but doing technically right installers on Windows is, in my opinion, way more obtuse and complicated than it should be, so this project does not distribute installers yet.

Therefore, to get PackSquash running, you've to do the steps that an installer would do manually. Luckily, this is a well-documented process: there are step-by-step instructions on how to do that in the [installation guide](https://github.com/ComunidadAylas/PackSquash/wiki/Installation-guide), in the "Windows installation section". That guide also highlights other means of getting PackSquash, which might be relevant for you if you decide to use PackSquash outside of your Windows computer.

Please try following the mentioned instructions in the installation guide to get your system set up to run PackSquash. If you need further assistance, don't hesitate getting back to us, preferably over Discord :smile:

**Comment by AlexTMjugador** [comment]
I can't reproduce this problem when installing PackSquash as documented, other users report that the installation instructions work, and I have not heard back from you in a week. Granted, I could try making PackSquash easier to run, but that is not in scope for this issue.

I'm closing this issue as resolved. Feel free to reach us out if you have any problems.
